services:
  app:
    image: ${DOCKER_USERNAME}/citizen-complaint:latest
    container_name: citizen-complaint-app
    restart: unless-stopped
    env_file: .env
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    ports:
      - "8000:8000"
    networks:
      - citizen-complaint-network

networks:
  citizen-complaint-network:
    driver: bridge
